### ISSUE TITLE
Error run test

### ISSUE THREAD

**Issue by menduong** [heroiclabs/nakama-js#134]
Anyone can run test with command?:
yarn workspace @heroiclabs/nakama-js-test run test
I follow readme steps then tried but error

**Comment by menduong** [comment]
@lugehorsam please help me view error. Thanks you!
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/menduong/.npm/_logs/2022-07-07T15_47_30_841Z-debug.log
menduong@MacBook-Pro-cua-menduong nakama-js-2.4.1 % more /Users/menduong/.npm/_logs/2022-07-07T15_47_30_841Z-debug.log
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'typescript',
0 verbose cli   '--project',
0 verbose cli   'tsconfig.test.json'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v16.13.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/menduong/Desktop/code/nodejs/nakama-js-2.4.1/packages/nakama-js-test/.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/menduong/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/menduong/.npm-global/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 3ms
19 timing npm:load:configload Completed in 4ms
20 timing npm:load:setTitle Completed in 5ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 0ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 12ms
27 http fetch GET 200 https://registry.npmjs.org/typescript 1377ms (cache updated)
28 timing command:exec Completed in 1416ms
29 verbose stack Error: could not determine executable to run
29 verbose stack     at getBinFromManifest (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:15:23)
29 verbose stack     at exec (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:113:15)
30 verbose pkgid typescript@4.7.4
31 verbose cwd /Users/menduong/Desktop/code/nodejs/nakama-js-2.4.1/packages/nakama-js-test
32 verbose Darwin 21.5.0
33 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "typescript" "--project" "tsconfig.test.json"
34 verbose node v16.13.1
35 verbose npm  v8.1.2
36 error could not determine executable to run
37 verbose exit 1
