### ISSUE TITLE
Authenticating Facebook Users Friends Causes Error

### ISSUE THREAD

**Issue by Chooster** [heroiclabs/nakama-js#19]
When I'm trying to register two users that are friends through FB on Nakama I'm getting a weird error saying, `Could not register: { "code": 6, "message": "ID already in use",`
Does anyone have any idea how that could be happening?
I'm not seeing any ID's between the two users that are the same.

The weird thing is I've test it many ways, I've cleared my backend database and registered 3 users in different orders.
When I do Un-friended, Un-friended both users register fine
if I do Un-friended, friended, friended it errors out on the 2nd friended user
Doesn't matter what the order of accounts are it always errors out on the 2nd friended user and will work fine for any users that aren't on each other friend's list.

It is going through the normal flow of authenticating a user, it is giving an error code 5 stating that the `{"code":5,"message":"ID not found","request":` and then giving an error of: `Error: { "code": 6, "message": "ID already in use", "request":`

It can be separated. If I `register John (friends with Nick), Greg (no friends in common, and Nick (friends with John) it will work until I register with Nick`

**Comment by Chooster** [comment]
We're running into an issue with having people use Facebook sign in and then go through the Nakama registration flow.

Here's the log:

```{"level":"debug","ts":"2018-03-15T00:23:49.979Z","msg":"Received message","server":"nakama-node-1","type":"*server.AuthenticateRequest_Facebook"}
{"level":"debug","ts":"2018-03-15T00:23:50.032Z","msg":"Could not retrieve user ID","server":"nakama-node-1","error":"ID not found","code":5}
{"level":"debug","ts":"2018-03-15T00:23:50.132Z","msg":"Received message","server":"nakama-node-1","type":"*server.AuthenticateRequest_Facebook"}
{"level":"debug","ts":"2018-03-15T00:23:50.207Z","msg":"Imported friends from Facebook","server":"nakama-node-1","user_id":"pTq38OcCQBKQF7WJmihQJw"}
{"level":"info","ts":"2018-03-15T00:23:50.208Z","msg":"http: panic serving <SOME_IP_ADDRESS>:53168: interface conversion: interface {} is []uint8, not string\ngoroutine 1396 [running]:\nnet/http.(*conn).serve.func1(0xc420299ae0)\n\t/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1697 +0xd0\npanic(0xb0f340, 0xc4203c9200)\n\t/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283\nnakama/server.(*pipeline).addFacebookFriends.func1(0xc42025c668, 0xc420561500, 0xc42025c5f0, 0xc42025c6d8, 0xc42020e620, 0xa, 0xc42020e600, 0xf, 0x162270a9e98, 0xc42016c460, ...)\n\tserver/pipeline_friend.go:119 +0x105c\nnakama/server.(*pipeline).addFacebookFriends(0xc42016c460, 0xc420561500, 0xc4202e1340, 0x16, 0xc42020e620, 0xa, 0xc42020e600, 0xf, 0xc4202764b0, 0xe7)\n\tserver/pipeline_friend.go:224 +0x1162\nnakama/server.(*authenticationService).register.func1(0xc42039a6e0, 0xc4202e1340, 0x16, 0xc42020e620, 0xa, 0xc42020e600, 0xf)\n\tserver/session_auth.go:783 +0x1ea\nnakama/server.(*authenticationService).register(0xc42037ca20, 0xc42039a6e0, 0xc42025ce70, 0x6dce0f, 0xc42008a2c0, 0xc420135800, 0x1, 0xb467a0, 0xc420678570)\n\tserver/session_auth.go:828 +0xa5d\nnakama/server.(*authenticationService).(nakama/server.register)-fm(0xc42039a6e0, 0xc4202eb9a0, 0xc4202b96c0, 0xc42039a6e0, 0xc42039a6e0, 0x0, 0x0, 0xc42039a000)\n\tserver/session_auth.go:160 +0x34\nnakama/server.(*authenticationService).handleAuth(0xc42037ca20, 0xf26ba0, 0xc4202fd180, 0xc4202ec700, 0xc42025db10)\n\tserver/session_auth.go:384 +0xf96\nnakama/server.(*authenticationService).configure.func4(0xf26ba0, 0xc4202fd180, 0xc4202ec700)\n\tserver/session_auth.go:160 +0x92\nnet/http.HandlerFunc.ServeHTTP(0xc420165c20, 0xf26ba0, 0xc4202fd180, 0xc4202ec700)\n\t/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1918 +0x44\nnakama/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42015acd0, 0xf26ba0, 0xc4202fd180, 0xc4202ec700)\n\tvendor/github.com/gorilla/mux/mux.go:103 +0x22b\nnakama/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc42028a240, 0xf26ba0, 0xc4202fd180, 0xc4202ec700)\n\tvendor/github.com/gorilla/handlers/cors.go:51 +0x98c\nnet/http.serverHandler.ServeHTTP(0xc42016ac30, 0xf26ba0, 0xc4202fd180, 0xc4202ec700)\n\t/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:2619 +0xb4\nnet/http.(*conn).serve(0xc420299ae0, 0xf27220, 0xc4203c88c0)\n\t/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1801 +0x71d\ncreated by net/http.(*Server).Serve\n\t/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:2720 +0x288","server":"nakama-node-1"}
{"level":"debug","ts":"2018-03-15T00:23:50.379Z","msg":"Sending *server.Envelope_Heartbeat message","server":"nakama-node-1","uid":"V3ZtpG-qSG-9cu-kTpruPA","sid":"U_ZACkvGSzWgatQlATizAQ","cid":""}
{"level":"debug","ts":"2018-03-15T00:23:50.388Z","msg":"Received message","server":"nakama-node-1","type":"*server.AuthenticateRequest_Facebook"}
{"level":"debug","ts":"2018-03-15T00:23:50.408Z","msg":"Could not retrieve user ID","server":"nakama-node-1","error":"ID already in use","code":6}```

Curious if you've ever seen that `http: panic serving <SOME_IP_ADDRESS>:53168: interface conversion: interface {} is []uint8, not string` issue?

We seem to be able to recreate it by logging in different users in different orders with varying degrees of friend connectivity but haven't yet tracked down what does and doesn't cause this error.

**Comment by mofirouz** [comment]
This is fixed in the main Nakama server repo. https://github.com/heroiclabs/nakama/commit/7277e37ff2c09803642fe5d13964345df31e636a
