### ISSUE TITLE
Socket related Issue

### ISSUE THREAD

**Issue by itsabubaker** [heroiclabs/nakama-js#205]
I am new to Nakama. And I am trying to send message in a group. My code is:
exports.sendGroupMessage = async (req, res) => {
	const errors = validationResult(req);
	if (!errors.isEmpty()) {
		return res.status(400).json({ errors: errors.array() });
	}
	
	const session = req.session;
	const { groupId, messageContent } = req.body;
	
	try {
		
		// Create Nakama socket using WebSocket adapter
		const socket = client.createSocket();
		console.log(socket);
		const appearOnline = true;
		const socketSession = await socket.connect(session, appearOnline);
		console.log(socketSession);
		// Join the group chat before sending the message
		const result = await socket.joinChat(groupId, 3, true, false); // Type 3 is for group chat
		console.log("Joined chat:", result);
		
		if (result) {
			// Send the group message
			const messageAck = await socket.writeChatMessage(groupId, messageContent);
			return res.json({ messageAck });
		} else {
			return res.status(400).json({ errors: [{ msg: 'Failed to join chat' }] });
		}
	} catch (error) {
		console.error('Failed to send group message:', error);
		const statusCode = error.status || 500;
		const statusText = error.statusText || 'Unknown error occurred';
		return res.status(statusCode).json({ errors: [{ msg: statusText }] });
	}
};

But I am getting following error:

Failed to send group message: ReferenceError: WebSocket is not defined
    at WebSocketAdapterText.isOpen (D:\TechShield\Github\Nakama\NakamaApiRepo\NakamaApi\node_modules\@heroiclabs\nakama-js\dist\nakama-js.cjs.js:3319:70)
    at _DefaultSocket.connect (D:\TechShield\Github\Nakama\NakamaApiRepo\NakamaApi\node_modules\@heroiclabs\nakama-js\dist\nakama-js.cjs.js:3370:22)
    at exports.sendGroupMessage (D:\TechShield\Github\Nakama\NakamaApiRepo\NakamaApi\controller\api\ChatController.js:130:38)
    at Layer.handle [as handle_request] (D:\TechShield\Github\Nakama\NakamaApiRepo\NakamaApi\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\TechShield\Github\Nakama\NakamaApiRepo\NakamaApi\node_modules\express\lib\router\route.js:149:13)
    at middleware (D:\TechShield\Github\Nakama\NakamaApiRepo\NakamaApi\node_modules\express-validator\lib\middlewares\check.js:16:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
    What problem is exactly? Can it be solved? Solution?

**Comment by mofirouz** [comment]
If I'm reading the stack correctly, you are using this library as part of a NodeJS application. This library only supports Web and not NodeJS. You can add NodeJS by adding your NodeJS WebSocket adapter. Feel free to open a PR with these changes. 

Also, for the future, development questions should be asked on https://forum.heroiclabs.com.

Thanks

**Comment by itsabubaker** [comment]
Can you share a relevant code snippet or tutorial for adding webSocket
Adapter to use Nakama real time chat?

**Comment by mofirouz** [comment]
You can take a look at [this adapter](https://github.com/heroiclabs/nakama-js/blob/master/packages/nakama-js/web_socket_adapter.ts) to add the NodeJS adapter.
