### ISSUE TITLE
Run test with newest server: 2 failed

### ISSUE THREAD

**Issue by kienvn** [heroiclabs/nakama-js#33]
1. test\socket-match.test.js
  ● Match Tests › should create match

    expect(received)[.not].toHaveLength(length)

    Expected value to have a 'length' property that is a number. Received:
      undefined

      56 |     expect(response.match).not.toBeNull();
      57 |     expect(response.match.match_id).not.toBeNull();
    > 58 |     expect(response.match.presences).toHaveLength(1);
      59 |     expect(response.match.self).not.toBeNull();
      60 |     expect(response.match.self.session_id).not.toBeNull();
      61 |     expect(response.match.self.user_id).not.toBeNull();

      at Object.it (test/socket-match.test.js:58:38)

2. test\client-authenticate.test.js
  ● Console
    console.log test\client-authenticate.test.js:33
      PAGE LOG ERROR: Error: Response
          at Page._handleException (D:\nakama-js-master\node_modules\puppeteer\lib\Page.js:409:38)
          at CDPSession.Page.client.on.exception (D:\nakama-js-master\node_modules\puppeteer\lib\Page.js:102:60)
          at emitOne (events.js:116:13)
          at CDPSession.emit (events.js:211:7)
          at CDPSession._onMessage (D:\nakama-js-master\node_modules\puppeteer\lib\Connection.js:215:12)
          at Connection._onMessage (D:\nakama-js-master\node_modules\puppeteer\lib\Connection.js:117:19)
          at emitOne (events.js:116:13)
          at WebSocket.emit (events.js:211:7)
          at Receiver._receiver.onmessage (D:\nakama-js-master\node_modules\ws\lib\WebSocket.js:141:47)
          at Receiver.dataMessage (D:\nakama-js-master\node_modules\ws\lib\Receiver.js:389:14)
  ● Authenticate Tests › should fail to authenticate with new custom id
    Evaluation failed: Response
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:75:13)

**Comment by novabyte** [comment]
All tests pass. I've updated the test harness to use the latest version of Puppeteer.
